### ISSUE TITLE
Is it possible to find a full list of the rule?

### ISSUE THREAD

**Issue by Lakr233** [AppleFoxUser42/macOS-Sandbox-Profiles#1]
Hi, i'm planing to write an app enabling sandbox-exec for user selected apps. I want to make an editor for the rule database. Would you like to share around?

**Comment by Ozymandias42** [comment]
Huh. It's been years since I last touched this but from what I remember I never accessed a database and Apple's documentation on this was.. let's say subpar. 

What I did was, as described in the readme, enabling debug mode and to just see what is being used.
Then copy paste the results and adapt them to be rules in their own right.

If you plan on writing an editor for this you'd have to implement this process there. There is no database with all possible rules. 
In fact there isn't one for AppArmor or SELinux either. Even there you have to read documentation and build your own according to what is stated there.

Hope I could be of help at least a little bit to you.
